apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
    app: backend

type: Opaque
data:
  REDIS_PASSWORD: "eW91cl9yZWRpc19wYXNzd29yZA=="  # base64 encoded value
  JWT_SECRET: "cG9rZXItZ2FtZS1iYWNrZW5k"  # base64 encoded value