apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
    app: backend

type: Opaque
data:
  REDIS_PASSWORD: "password=="  # base64 encoded value
  JWT_SECRET: ""  # base64 encoded value