apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend

data:
  NODE_ENV: "stag"
  HOST: "0.0.0.0"
  PORT: "3000"
  BASE_URL: "http://21hodeem:3000"
  BASE_API_PATH: "http://21hodeem:3000/api/v1"
  DB_URL: "mongodb://mongodb:27017/poker-game"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_USERNAME: "default"
  BULL_HOST: "redis"
  FRONTEND_URL: "https://game.virals.studio"