apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
    app: backend

type: Opaque
data:
  REDIS_PASSWORD: "cGFzc3dvcmQ="  # Base64 for "password"
  MONGO_ROOT_PASSWORD: "WXVkaXpAMzIx"  # Base64 for "Yudiz@321"
  JWT_SECRET: "cG9rZXItZ2FtZS1iYWNrZW5k"  # Base64 encoded value
