apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend

data:
  NODE_ENV: "stag"
  HOST: "0.0.0.0"
  PORT: "3000"
  BASE_URL: "https://21hodeem:3000"
  BASE_API_PATH: "https://21hodeem:3000/api/v1"
  DB_URL: "mongodb://my-mongo-mongodb.default.svc.cluster.local:27017/"
  REDIS_HOST: "redis-cluster-master.default.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_USERNAME: "default"
  BULL_HOST: "redis-cluster-master.default.svc.cluster.local"
  FRONTEND_URL: "https://game.virals.studio"
