apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend

data:
  NODE_ENV: "dev"
  HOST: "0.0.0.0"
  PORT: "3000"

  # Base URLs
  BASE_URL: "https://backend:3000"
  BASE_API_PATH: "https://backend:3000/api/v1"
  FRONTEND_URL: "https://fronted"

  # Database
  DB_URL: "mongodb+srv://root:password@cluster/game?authSource=admin"

  # Redis Configuration
  REDIS_HOST: "redis.ap-south-1-1.ec2.redns.redis-cloud.com"
  REDIS_PORT: "14722"
  REDIS_USERNAME: "default" 
  REDIS_PASSWORD: "password"
  BULL_HOST: "redis.ap-south-1-1.ec2.redns.redis-cloud.com"



